//  valueが0だとDBへの登録の問題で外部サイトに反映されなくなるから、その時はAdd_girlとEdit_girlのDBへの登録のコードを変えた方がいいよ

// OHP各種フラグ
export const flags = [
  { value: '1', label: 'ピックアップ' },
  { value: '2', label: 'PCR検査済' },
  { value: '3', label: 'ワクチン接種済' },
  { value: '4', label: 'マット対応' },
  { value: '5', label: 'サービス抜群' },
  { value: '6', label: '感度抜群' },
  { value: '7', label: '業界未経験' },
  { value: '8', label: '責め上手' },
  { value: '9', label: '言葉責め' },
  { value: '10', label: '元気系' },
  { value: '11', label: '癒し系' },
  { value: '12', label: 'おっとり' },
  { value: '13', label: 'ﾓﾆﾀｰｺｰｽ対応中' },
];

// カップ
export const cups = [
  { value: '', label: '-' },
  { value: '1', label: 'A' },
  { value: '2', label: 'B' },
  { value: '3', label: 'C' },
  { value: '4', label: 'D' },
  { value: '5', label: 'E' },
  { value: '6', label: 'F' },
  { value: '7', label: 'G' },
  { value: '8', label: 'H' },
  { value: '9', label: 'I' },
  { value: '10', label: 'J' },
  { value: '11', label: 'K' },
  { value: '12', label: 'L' },
  { value: '13', label: 'M' },
  { value: '14', label: 'N' },
  { value: '15', label: 'O' },
  { value: '16', label: 'P' },
  { value: '17', label: 'Q' },
  { value: '18', label: 'R' },
  { value: '19', label: 'S' },
  { value: '20', label: 'T' },
  { value: '21', label: 'U' },
  { value: '22', label: 'V' },
  { value: '23', label: 'W' },
  { value: '24', label: 'X' },
  { value: '25', label: 'Y' },
  { value: '26', label: 'Z' },
];

// オフィシャル
export const sellingPoints = [
    { value: '1', label: 'ルックス抜群' },
    { value: '2', label: 'スタイル抜群' },
    { value: '3', label: 'サービス抜群' },
    { value: '4', label: '感度抜群' },
    { value: '5', label: '清楚' },
    { value: '6', label: '巨乳' },
    { value: '7', label: '爆乳' },
    { value: '8', label: 'スレンダー' },
    { value: '9', label: '業界未経験' },
    { value: '10', label: '小柄' },
    { value: '11', label: '長身' },
    { value: '12', label: '美乳' },
    { value: '13', label: 'ドM' },
    { value: '14', label: 'ドS' },
    { value: '15', label: '責め上手' },
    { value: '16', label: 'ソフトS' },
    { value: '17', label: 'ソフトM' },
    { value: '18', label: '黒髪' },
    { value: '19', label: 'ショートカット' },
    { value: '20', label: '言葉責め' },
    { value: '21', label: '妹' },
    { value: '22', label: 'ロリ' },
    { value: '23', label: 'モデル' },
    { value: '24', label: '姉ギャル' },
    { value: '25', label: 'ボーイッシュ' },
    { value: '26', label: '元気系' },
    { value: '27', label: '色白' },
    { value: '28', label: '癒し系' },
    { value: '29', label: 'キレカワ' },
    { value: '30', label: 'おっとり' },
    { value: '31', label: 'アイドル' },
    { value: '32', label: '変態' },
    { value: '33', label: '淫乱' },
];

// シティヘブン
export const chSellingPoints = [
    { value: '07', label: 'スレンダー' },
    { value: '08', label: 'ぷよっ子' },
    { value: '09', label: '小柄' },
    { value: '10', label: '長身' },
    { value: '21', label: '普通' },
    { value: '22', label: 'グラマー' },
    { value: '23', label: 'ぽっちゃり' },
    { value: '05', label: '素人' },
    { value: '06', label: '巨乳' },
    { value: '11', label: '美乳' },
    { value: '12', label: '美脚' },
    { value: '55', label: '美尻' },
    { value: '13', label: 'パイパン' },
    { value: '24', label: 'ギャル系' },
    { value: '25', label: 'モデル系' },
    { value: '26', label: '現役学生' },
    { value: '27', label: 'セクシー女優' },
    { value: '28', label: 'ハーフ' },
    { value: '29', label: 'アニメ声' },
    { value: '30', label: '黒髪' },
    { value: '31', label: 'ニューハーフ' },
    { value: '56', label: 'レズビアン' },
    { value: '32', label: '乳首ピンク' },
    { value: '33', label: '乳輪大きい' },
    { value: '54', label: '喫煙しない' },
    { value: '14', label: '明るい' },
    { value: '15', label: '癒し系' },
    { value: '34', label: '甘えん坊' },
    { value: '35', label: '天然' },
    { value: '36', label: 'ツンデレ' },
    { value: '37', label: 'おっとり' },
    { value: '38', label: '恥ずかしがり屋' },
    { value: '39', label: '人懐っこい' },
    { value: '40', label: 'エロい' },
    { value: '41', label: '空気を読む' },
    { value: '42', label: 'オタク' },
    { value: '43', label: 'しっかり者' },
    { value: '01', label: 'ルックス抜群' },
    { value: '02', label: 'スタイル抜群' },
    { value: '03', label: 'サービス抜群' },
    { value: '04', label: '感度抜群' },
    { value: '16', label: '責め好き' },
    { value: '17', label: '受け身好き' },
    { value: '19', label: 'ア〇ル' },
    { value: '20', label: 'マニア' },
    { value: '44', label: '潮吹き' },
    { value: '45', label: 'ドM' },
    { value: '46', label: 'ドS・女王様' },
    { value: '47', label: '変態' },
    { value: '48', label: '話し好き' },
    { value: '49', label: '聞き上手' },
    { value: '50', label: '母乳' },
    { value: '51', label: 'パイズリ' },
    { value: '52', label: '聖水' },
    { value: '53', label: '黄金' },
];

// 駅ちか
export const ecSellingPoints = [
    { value: '1', label: 'no1' },
    { value: '2', label: 'no2' },
    { value: '3', label: 'no3' },
    { value: '4', label: 'プレミア' },
    { value: '5', label: '店長オススメ' },
    // { value: '24', label: 'av女優' },
    { value: '38', label: '素人' },
    { value: '40', label: '未経験' },
    { value: '46', label: '禁煙' },
    { value: '51', label: '要予約' },
    { value: '59', label: '顔出し' },
    { value: '75', label: 'アジアン' },
    { value: '76', label: 'ブロンド・金髪' },
    { value: '61', label: 'ニューハーフ' },
    { value: '7', label: 'アイドル系' },
    { value: '8', label: 'お姉さん系' },
    { value: '62', label: '熟女系' },
    { value: '9', label: 'お嬢様' },
    { value: '10', label: '可愛い系' },
    { value: '11', label: 'ロリ系' },
    { value: '14', label: 'ギャル系' },
    { value: '15', label: 'キレカワ' },
    { value: '21', label: '美少女系' },
    { value: '23', label: '綺麗系' },
    { value: '56', label: 'ハーフ' },
    { value: '16', label: 'グラマー' },
    { value: '17', label: 'スレンダー' },
    { value: '19', label: 'ぽっちゃり' },
    // { value: '26', label: 'パイパン' },
    { value: '27', label: 'ミニマム' },
    { value: '28', label: '巨乳' },
    { value: '29', label: '爆乳' },
    { value: '63', label: '貧乳' },
    { value: '30', label: '美乳' },
    { value: '64', label: '巨尻' },
    { value: '31', label: '美尻' },
    { value: '33', label: '美肌' },
    { value: '34', label: '美脚' },
    { value: '36', label: '色白' },
    { value: '42', label: 'スタイル抜群' },
    { value: '45', label: 'モデル系' },
    { value: '58', label: '高身長' },
    { value: '65', label: '低身長' },
    // { value: '66', label: '妊婦プレイ' },
    { value: '67', label: 'タトゥー・刺青' },
    { value: '6', label: 'OL系' },
    { value: '12', label: '女子大生' },
    { value: '13', label: 'キャバ系' },
    { value: '18', label: 'セクシー系' },
    { value: '20', label: '人妻系' },
    { value: '22', label: '癒し系' },
    { value: '49', label: '清楚' },
    { value: '50', label: '萌え系' },
    { value: '52', label: 'おっとり' },
    { value: '54', label: '天然' },
    { value: '25', label: 'テクニシャン' },
    // { value: '35', label: '敏感' },
    { value: '41', label: 'サービス抜群' },
    { value: '43', label: '愛嬌抜群' },
    { value: '44', label: 'ｲﾁｬｲﾁｬ好き' },
    // { value: '47', label: '攻め好き' },
    // { value: '48', label: '受身好き' },
    // { value: '53', label: '痴女' },
    // { value: '55', label: '濃厚サービス' },
    // { value: '57', label: '潮吹き' },
    // { value: '60', label: 'ドM（ドエム）' },
    // { value: '68', label: 'ドS（ドエス）' },
    // { value: '69', label: '母乳プレイ' },
    // { value: '70', label: 'パイズリ' },
    // { value: '71', label: 'AF可' },
    // { value: '72', label: 'イラマチオ可' },
    // { value: '73', label: '3P可' },
    // { value: '74', label: 'ごっくん' },
];

// ぴゅあらば
export const plSellingPoints = [
    { value: '1', label: '素人系' },
    { value: '2', label: '人妻系' },
    { value: '3', label: '幼妻･若妻' },
    { value: '4', label: '熟女系' },
    { value: '5', label: 'ロリ･妹系' },
    { value: '6', label: 'ロリ巨乳' },
    { value: '7', label: '痴女･S女' },
    { value: '8', label: 'M女･ドM' },
    { value: '9', label: 'AV女優' },
    { value: '10', label: '女子大生' },
    { value: '11', label: '外国人(金髪･ブロンド)' },
    { value: '12', label: 'レズビアン' },
    { value: '13', label: 'ニューハーフ' },
    { value: '14', label: 'バイセクシュアル' },
    { value: '19', label: 'お姉さん系' },
    { value: '20', label: '美女･モデル系' },
    { value: '21', label: '美少女･可愛い系' },
    { value: '22', label: 'アイドル系' },
    { value: '23', label: 'ギャル･黒ギャル' },
    { value: '24', label: 'キャンギャル系' },
    { value: '25', label: 'OL･秘書' },
    { value: '26', label: 'キャバ系' },
    { value: '27', label: 'お嬢様系' },
    { value: '28', label: '女子アナ系' },
    { value: '29', label: '清楚系' },
    { value: '30', label: 'キレカワ系' },
    { value: '31', label: 'ゆるふわ系' },
    { value: '32', label: '色白' },
    { value: '33', label: '激似･そっくり系' },
    { value: '43', label: '巨乳' },
    { value: '44', label: '爆乳' },
    { value: '45', label: '美乳' },
    { value: '46', label: '微乳･貧乳' },
    { value: '48', label: 'スレンダー' },
    { value: '49', label: '美脚' },
    { value: '50', label: '色黒･日焼け' },
    { value: '51', label: '妊婦' },
    { value: '55', label: 'ショートヘア' },
    { value: '56', label: 'ストレートロング' },
];

// 風俗じゃぱん
export const fjSellingPoints1 = [
  { value: '64', label: '美乳' },
  // { value: '79', label: '乳輪大きい' },
  // { value: '78', label: '乳首ピンク' },
  { value: '65', label: '美尻' },
  { value: '66', label: '巨尻' },
  { value: '29', label: 'スレンダー' },
  { value: '30', label: 'セクシー' },
  { value: '28', label: 'グラマー' },
  { value: '62', label: 'ぽっちゃり' },
  { value: '90', label: 'メガぽっちゃり' },
  { value: '71', label: '美肌' },
  { value: '74', label: '色白' },
  { value: '100', label: '色黒' },
  // { value: '70', label: 'パイパン' },
  { value: '77', label: '黒髪' },
  { value: '72', label: '美脚' },
];

export const fjSellingPoints2 = [
  { value: '47', label: '明るい' },
  { value: '48', label: '甘えん坊' },
  { value: '49', label: 'ツンデレ' },
  { value: '50', label: '恥ずかしがり屋' },
  { value: '51', label: '人懐っこい' },
  { value: '37', label: '愛嬌抜群' },
  { value: '55', label: 'しっかり者' },
  { value: '60', label: '話し好き' },
  { value: '61', label: '聞き上手' },
  { value: '41', label: '天然' },
  { value: '54', label: 'オタク' },
  { value: '39', label: 'おっとり' },
  { value: '38', label: 'ｲﾁｬｲﾁｬ好き' },
];

export const fjSellingPoints3 = [
  { value: '20', label: 'ロリ系' },
  { value: '26', label: 'ギャル系' },
  { value: '22', label: '人妻系' },
  { value: '33', label: 'キレイ系' },
  { value: '32', label: 'カワイイ系' },
  { value: '34', label: 'モデル系' },
  { value: '23', label: '美少女系' },
  { value: '24', label: '癒し系' },
  { value: '25', label: 'キャバ系' },
  { value: '40', label: '清楚' },
  { value: '17', label: 'アイドル系' },
  { value: '16', label: 'OL系' },
  { value: '18', label: 'お姉さん系' },
  { value: '31', label: '萌え系' },
  { value: '19', label: 'お嬢様' },
];

export const fjSellingPoints4 = [
  // { value: '84', label: '黄金' },
  // { value: '83', label: '聖水' },
  // { value: '85', label: 'マット' },
  // { value: '86', label: 'アナル' },
  // { value: '87', label: 'パイズリ' },
  // { value: '82', label: '潮吹き' },
];

export const fjSellingPoints5 = [
  // { value: '5', label: 'AV女優' },
  // { value: '88', label: '母乳' },
  { value: '13', label: 'ニューハーフ' },
  // { value: '73', label: '敏感' },
  // { value: '57', label: '感度抜群' },
  { value: '21', label: '女子大生' },
  { value: '81', label: 'スタイル抜群' },
  { value: '14', label: 'ハーフ' },
  { value: '15', label: 'タトゥー' },
  { value: '6', label: '素人' },
  // { value: '59', label: '変態' },
  // { value: '89', label: '痴女' },
  { value: '56', label: 'アニメ声' },
  { value: '4', label: '未経験' },
  { value: '11', label: '顔出し' },
  { value: '9', label: '禁煙' },
  { value: '44', label: 'テクニシャン' },
];